### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xswirelab** [buddy/terraform-provider-buddy#18]
Hi @mical,

sorry for bothering you, but if you don’t mind, I have a few questions.

I’ve just recently gotten a new job and my first assignments had me going through loads of SaaS. Like aws(s3,MediaConvert,iam,CloudFront), Buddy, Azure, GitHub, to name a few.
So I looked around to find tooling to make it easier to manage all that stuff and came across Terraform.

I am slightly getting the hang of it but because I am still new and eager to learn, I was wondering if you could show me an example of how I would set up a Buddy pipeline with your provider.
The examples you have given might start to speak to me in a few weeks, but for now I am swimming and can’t get a good picture of how I would set up a terraform module specifically for PHP projects with your Buddy provider.
Could you maybe help me towards the right direction?

**Comment by mical** [comment]
Hello,
we are in the middle of developing terraform module for buddy and it does not cover full api yet (specifically the actions within pipeline). The best way to manage pipelines right now is through [yaml](https://buddy.works/docs/yaml/yaml-gui). You can for example create repo on GitHub with buddy.yml. Next use terraform to create project in Buddy - integrated with this GitHub repo. After that pipelines will be automatically visible in the Buddy project. Example:

```yml
terraform {
  required_providers {
    buddy = {
      source = "buddy/buddy"
      version = "1.4.0"
    }
  }
}
provider "buddy" {
  token = "..."
}
resource "buddy_project" "myproject" {
  domain              = "buddy_domain"
  display_name        = "myproject"
  integration_id      = "githubIntegrationId"
  external_project_id = "gh_account/repo"
}
```

GitHub Integration within Buddy must be first created ([docs](https://buddy.works/docs/integrations/github/github)).
