### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by okvic77** [buddy/terraform-provider-buddy#36]
Hi guys, all this is good stuff. This helps a lot at work!

Do you have on the roadmap releasing `actions` block? Or a way to "clone" actions from a template pipeline? I am able to create a brand new pipeline but not able to put some actions in it. My current process is to clone from another pipeline and updating a variable.

Thanks!!!

**Comment by mical** [comment]
In the future we may add this feature but we dont have any date.
For now you these options:
* keep pipeline yaml in external project like github - in terraform create project from these repository
* use remote definition (template) - create pipeline in terraform and point yaml definition to some other project
```
resource "buddy_pipeline" "remote" {
  domain              = "mydomain"
  project_name        = "myproject"
  name                = "remote_pipeline"
  definition_source   = "REMOTE"
  remote_project_name = "remote_project"
  remote_branch       = "remote_branch"
  remote_path         = "remote.yml"

  remote_parameter {
    key   = "myparam"
    value = "val"
  }
}
