### ISSUE TITLE
Better documentation please

### ISSUE THREAD

**Issue by SamCrudge** [buddy/terraform-provider-buddy#9]
**Is your feature request related to a problem? Please describe.**
More examples of how data is meant to be passed to optional variables please

**Describe the solution you'd like**
More individual examples/ more concise description

**Additional context**

This was encountered while working on the resource "buddy_pipeline".
![Screenshot 2022-02-20 at 15-09-04 buddy_pipeline Resources buddy buddy Terraform Registry](https://user-images.githubusercontent.com/37799019/154849378-8e778734-31ea-4719-8d91-0ff99fc42a45.png)

This error message is telling me this optional attribute is not expected in the resource?
What is a block of type Event?

I've had exactly the same issue with trigger_condition aswell
<img width="695" alt="image" src="https://user-images.githubusercontent.com/37799019/154849413-a9f98337-cf1a-4053-bcd1-621554f661e8.png">

**Comment by mical** [comment]
We've added more examples for resources in a new version: 
https://registry.terraform.io/providers/buddy/buddy/latest/docs/resources/buddy_pipeline

Besides this in Schema documentation there is:

event (Block List) The pipeline's list of events. Set it if on: EVENT (see [below for nested schema](https://registry.terraform.io/providers/buddy/buddy/latest/docs/resources/buddy_pipeline#nestedblock--event))

Therefor event is a list of blocks with refs & type props. Block List in terraform is always something like this:

```
event {
   ...
}
event {
   ...
}
